# Generated by Django 2.2.6 on 2022-12-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20221113_1726'),
        ('posts', '0004_auto_20210427_2331'),
    ]

    operations = [
    ]
